name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _anaconda_depends=2024.10
  - aiobotocore=2.12.3
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aioitertools=0.7.1
  - aiosignal=1.2.0
  - alabaster=0.7.16
  - altair=5.0.1
  - anaconda-anon-usage=0.4.4
  - anaconda-catalogs=0.2.0
  - anaconda-client=1.12.3
  - anaconda-cloud-auth=0.5.1
  - anaconda-navigator=2.6.3
  - anaconda-project=0.11.1
  - anaconda_powershell_prompt=1.1.0
  - anaconda_prompt=1.1.0
  - annotated-types=0.6.0
  - anyio=4.2.0
  - aom=3.6.0
  - appdirs=1.4.4
  - archspec=0.2.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - arrow-cpp=16.1.0
  - astroid=2.14.2
  - astropy=6.1.3
  - astropy-iers-data=0.2024.9.2.0.33.23
  - asttokens=2.0.5
  - async-lru=2.0.4
  - atomicwrites=1.4.0
  - attrs=23.1.0
  - automat=20.2.0
  - autopep8=2.0.4
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.8.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - blosc=1.21.5
  - bokeh=3.6.0
  - boltons=23.0.0
  - boost-cpp=1.82.0
  - botocore=1.34.69
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.12.0
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - certifi=2025.10.5
  - cffi=1.17.1
  - cfgrib=0.9.15.0
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.1
  - conda=24.11.3
  - conda-build=24.9.0
  - conda-content-trust=0.2.0
  - conda-index=0.5.0
  - conda-libmamba-solver=24.9.0
  - conda-pack=0.7.1
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - conda-repo-cli=1.0.114
  - conda-token=0.5.0
  - constantly=23.10.4
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - cryptography=43.0.0
  - cssselect=1.2.0
  - curl=8.15.0
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask=2024.8.2
  - dask-core=2024.8.2
  - dask-expr=1.1.13
  - datashader=0.16.3
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.8
  - distributed=2024.8.2
  - distro=1.9.0
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.7.1
  - filelock=3.13.1
  - findlibs=0.1.2
  - flake8=7.0.0
  - flask=3.0.3
  - fmt=9.1.0
  - fonttools=4.51.0
  - freeglut=3.4.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozendict=2.4.2
  - frozenlist=1.4.0
  - fsspec=2024.6.1
  - gdal=3.11.0
  - gensim=4.3.3
  - geos=3.10.6
  - geotiff=1.7.0
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glog=0.5.0
  - greenlet=3.0.1
  - h11=0.14.0
  - h5py=3.13.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - heapdict=1.0.1
  - holoviews=1.19.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - hvplot=0.11.0
  - hyperlink=21.0.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - imagecodecs=2024.9.22
  - imageio=2.33.1
  - imagesize=1.4.1
  - imbalanced-learn=0.12.3
  - importlib-metadata=7.0.1
  - incremental=22.10.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=2.0.7
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.28.0
  - ipython=8.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - isort=5.13.2
  - itemadapter=0.3.0
  - itemloaders=1.1.0
  - itsdangerous=2.2.0
  - jaraco.classes=3.2.1
  - jasper=4.2.4
  - jedi=0.19.1
  - jellyfish=1.0.1
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab-variableinspector=3.1.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.10.0
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libarchive=3.7.7
  - libavif=1.1.1
  - libboost=1.82.0
  - libboost-headers=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcurl=8.15.0
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgdal-core=3.11.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblief=0.12.3
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.9.2
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzip=1.10.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvmlite=0.43.0
  - locket=1.0.0
  - lxml=5.2.1
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - menuinst=2.1.2
  - minizip=4.0.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - more-itertools=10.3.0
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - msys2-conda-epoch=20160418
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - navigator-updater=0.5.1
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nltk=3.9.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.5.4
  - orc=2.0.1
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - panel=1.5.2
  - param=2.1.1
  - paramiko=2.8.1
  - parsel=1.8.1
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.10.3
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkce=1.0.3
  - platformdirs=3.10.0
  - plotly=5.24.1
  - pluggy=1.0.0
  - ply=3.11
  - proj=9.3.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protego=0.1.16
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-lief=0.12.3
  - pyarrow=16.1.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=5
  - pycodestyle=2.11.1
  - pycosat=0.6.6
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.3
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydeck=0.8.0
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.4
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pylint=2.16.2
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyodbc=5.1.0
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - pytables=3.9.2
  - pytest=7.4.4
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-eccodes=1.7.1
  - python-json-logger=2.0.7
  - python-libarchive-c=5.1
  - python-lmdb=1.4.1
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.10.0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytoolconfig=1.2.6
  - pytz=2024.1
  - pyviz_comms=3.0.2
  - pywavelets=1.7.0
  - pywin32=305
  - pywin32-ctypes=0.2.2
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - queuelib=1.6.2
  - re2=2022.04.01
  - referencing=0.30.2
  - regex=2024.9.11
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - requests-file=1.5.1
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rope=1.12.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.17.21
  - s3fs=2024.6.1
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - scrapy=2.11.1
  - seaborn=0.13.2
  - semver=3.0.2
  - send2trash=1.8.2
  - service_identity=18.1.0
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=5.5.1
  - spyder-kernels=2.5.0
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - streamlit=1.37.1
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tblib=1.7.0
  - tenacity=8.2.3
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.14
  - tldextract=5.1.2
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - truststore=0.8.0
  - twisted=23.10.0
  - twisted-iocpsupport=1.0.2
  - tzdata=2024b
  - uc-micro-py=1.0.1
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - uriparser=0.9.8
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - vc=14.40
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - w3lib=2.1.2
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - whatthepatch=1.0.2
  - wheel=0.44.0
  - widgetsnbextension=3.6.6
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.14.1
  - xarray=2023.6.0
  - xerces-c=3.2.5
  - xlwings=0.32.1
  - xyzservices=2022.9.0
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.40.2
  - yarl=1.11.0
  - zeromq=4.3.5
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=5.4.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - affine==2.4.0
      - astunparse==1.6.3
      - build==1.2.2.post1
      - cachecontrol==0.14.2
      - cdsapi==0.7.6
      - cftime==1.6.4.post1
      - cleo==2.1.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - comtypes==1.4.10
      - crashtest==0.4.1
      - distlib==0.3.9
      - dnspython==2.7.0
      - dulwich==0.22.8
      - eccodes==2.43.0
      - ecmwf-datastores-client==0.4.0
      - email-validator==2.2.0
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - fastjsonschema==2.21.1
      - findpython==0.6.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - gtts==2.5.4
      - httptools==0.6.4
      - huggingface-hub==0.29.3
      - installer==0.7.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jinja2==3.1.6
      - keras==3.11.3
      - keyring==25.6.0
      - libclang==18.1.1
      - ml-dtypes==0.5.3
      - mock==5.2.0
      - multiurl==0.3.7
      - namex==0.1.0
      - netcdf4==1.7.2
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.17.0
      - orjson==3.10.15
      - patchify==0.2.3
      - pbs-installer==2025.2.12
      - pkginfo==1.12.1.2
      - playsound==1.3.0
      - poetry-core==2.1.1
      - protobuf==5.29.5
      - pydantic-extra-types==2.10.3
      - pydantic-settings==2.8.1
      - pypiwin32==223
      - pyproject-hooks==1.2.0
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pyttsx3==2.98
      - questionary==2.1.0
      - rapidfuzz==3.12.2
      - rasterio==1.4.3
      - relaxml==0.1.3
      - rich-toolkit==0.13.2
      - safetensors==0.5.3
      - shap==0.46.0
      - shellingham==1.5.4
      - simplejson==3.20.1
      - slicer==0.0.8
      - starlette==0.46.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - three==0.8.0
      - tokenizers==0.21.1
      - tomlkit==0.13.2
      - torch==2.9.1
      - torchvision==0.24.1
      - transformers==4.49.0
      - trove-classifiers==2025.3.3.18
      - typer==0.15.2
      - typing-extensions==4.12.2
      - uvicorn==0.34.0
      - virtualenv==20.29.3
      - watchfiles==1.0.4
      - websockets==15.0.1
      - xlsxwriter==3.2.2

